export enum Action {
  SEND_MESSAGE_TO_DISCORD = 3,
  INVITE_5_FRIENDS_TO_DISCORD = 10,
  VISIT_GAME_TRADE_7_DAYS = 11,
  LINK_DISCORD_TO_YOUR_PROFILE = 5,
  COMMENT_5_ITEMS = 9,
  REPORT_ON_TWITTER = 4,
  FILL_A_POOL_DISCORD = 2,
  INVITE_FRIEND = 1,
  JOIN_DISCORD_CHANNEL = 6,
  BUY_ITEM = 7,
  LINK_TWITTER = 8,
}
